### PR TITLE
do not mask java.xml imports

### PR DESCRIPTION
**Pull request by maggu2810**
See #129

### CODE REVIEW

**Comment by hstaudacher** [comment]
thanks for this. Isn't removing the !import enough? Why are there binary files in this request?

**Comment by maggu2810** [comment]
The PR themselves does not contain any binary files.
I added a binary to another repo and referenced this PR in that commit message. Github adds a link, but this does not change the content of the branch that should me merged.

**Comment by maggu2810** [comment]
Removing the import mask is enough

**Comment by hstaudacher** [comment]
Ah alright, thanks for clarifying this.

**Comment by maggu2810** [comment]
Do you wait for something I should do?

**Comment by maggu2810** [comment]
I see you have done it with 6c7f8215f621657be2f9256625a24eddb4d82493
Do you not want to use pull requests?

**Comment by maggu2810** [comment]
As there is no response, I assume there is no interest upstream.

**Pull request closed without merging**
